GET http://localhost:3000/game/state

###

GET http://localhost:3000/game/start

###

GET http://localhost:3000/game/end

###

POST http://localhost:3000/teams/addMember
Content-Type: application/json

{
    "userID": "5a2643e84b885a0f306e75818ef556e8",
    "team": 1
}

###

GET http://localhost:3000/teams/member-exists?userID=5a2643e84b885a0f306e75818ef556e8