GET http://localhost:3000/game/state

###

GET http://localhost:3000/game/start

###

GET http://localhost:3000/game/end

###

POST http://localhost:3000/teams/members/add
Content-Type: application/json

{
    "user": {
        "name": "",
        "ID": "f99d76d121c98d4b88b65f3956181835",
        "inTeam": false,
        "teamId": -1
    },
    "teamName": "Team Blau",
    "teamID": 2
}

###

GET http://localhost:3000/teams/members/exists?userID=5edb227ad89fa9e840c3e770b949cac3

###

GET http://localhost:3000/user/instantiate?userID=f99d76d121c98d4b88b65f3956181835

###

POST  http://localhost:3000/game/buyRoad
Content-Type: application/json

{
    "roadName": "Salt Lake City - Helena",
    "teamId": 1
}

###
POST http://localhost:3000/team/goals/accept
Content-Type: application/json

{
    "teamColor" : "blue",
    "connection" : ["Winnipeg","Oklahoma City"]
}
###
POST http://localhost:3000/team/goals/check
Content-Type: application/json

{
    "teamColor" : "blue",
    "connection" : ["Vancouver","Kansas City"]
}